# Generated by Django 5.2.14 on 2026-09-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('send_private_email', 'Can Send Private Email To User By the Button')]},
        ),
    ]
